### PR TITLE
MAX-10493 Add hover color for trigger icon

### PR DESCRIPTION
**Pull request by benjaminliugang**
Added focus color for trigger icon.

### CODE REVIEW

**Review by evanjd — CHANGES_REQUESTED** [review]
Thanks for the contribution. Please remove your changes the `HISTORY.md` and `package.json` - we'll update this for you when a change is merged.

Also, it looks like your commits have been made with an e-mail not linked with your github account - this is why the CLA check is failing. Please rebase and update your commit e-mail to match what's on your profile.

**Comment by benjaminliugang** [comment]
test again

**Comment by evanjd** [comment]
@cla-bot check

**Comment by benjaminliugang** [comment]
@evanjd How can I check the failed reason for `The Travis CI build failed`?

**Comment by evanjd** [comment]
@benjaminliugang Click the `Details` link for the build log. The build failure isn't from your changes so you don't need to worry about fixing anything.

I'm working on the broken tests now, will merge the fixed tests into your branch ASAP.

**Comment by benjaminliugang** [comment]
Already find the error log, it seems the failed tests are not caused by change.
https://travis-ci.org/predixdesignsystem/px-product-switcher/builds/465288484?utm_source=github_status&utm_medium=notification

**Comment by evanjd** [comment]
Tests fixed on `master`, merging.

**Comment by benjaminliugang** [comment]
@evanjd , Thanks!

**Pull request merged**
